### ISSUE TITLE
NameError when adding params to a preview

### ISSUE THREAD

**Issue by unikitty37** [ViewComponent/lookbook#383] opened 2023-03-29 11:45 UTC
> **Before opening an issue** please make sure you have consulted the [Lookbook documentation](https://lookbook.build) (in particular the [Troubleshooting section](https://lookbook.build/guide/troubleshooting/)) and have checked the existing issues to see if this has already been reported.

### Describe the bug

When adding dynamic parameters, a NameError is generated:

`uninitialized constant #<Class:#<YARD::CodeObjects::MethodObject:0x0000ffff14ae8080>>::TITLE`

### To Reproduce

Steps to reproduce the behaviour:

- Create a component called TestComponent that takes a `title` parameter.

#### test_component.rb
```ruby
# frozen_string_literal: true

class TestComponent < ApplicationComponent
  attr_reader :title

  def initialize(title:)
    super

    @title = title
  end
end
```

#### test_component.html.erb
```html
<div><%= title %></div>
```

- Create a preview file.

#### test_component_preview.rb
```ruby
# frozen_string_literal: true

class TestComponentPreview < Lookbook::Preview
  TITLE = 'A default title'

  # @param title text
  def default(title: TITLE)
    render TestComponent.new(title: title)
  end
end
```

- Attempt to view the component in Lookbook.

### Expected behaviour

The component preview is rendered in Lookbook without errors.

### Screenshots

(none, but see the full error text below)

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.0.beta.8
* ViewComponent: 2.82.0
* Rails: 6.0.5.1
* Ruby: 2.7.4p191 (2021-07-07 revision a21a3b7d23) [aarch64-linux]
* Yard: 0.9.28

### Additional context

Removing the `# @param title text` line allows the component to render, but the title is no longer changeable by the viewer.

I'm not sure if this is Zeitwerk-related; we had to rename some files just to get Rails to start once the lookbook gem was added, even though it started just fine without the gem in place. Does Lookbook make any changes to the autoloader configuration?

Full error text:

```
NameError
uninitialized constant #<Class:#<YARD::CodeObjects::MethodObject:0x0000ffff14ae8080>>::TITLE
(eval) [line 1]
Full stack trace:
(eval):1:in `value_default'
/usr/local/bundle/gems/lookbook-2.0.0.beta.8/lib/lookbook/tags/param_tag.rb:31:in `instance_eval'
/usr/local/bundle/gems/lookbook-2.0.0.beta.8/lib/lookbook/tags/param_tag.rb:31:in `value_default'
/usr/local/bundle/gems/lookbook-2.0.0.beta.8/lib/lookbook/param.rb:58:in `from_tag'
/usr/local/bundle/gems/lookbook-2.0.0.beta.8/app/controllers/concerns/lookbook/targetable_concern.rb:71:in `block in set_params'
/usr/local/bundle/gems/lookbook-2.0.0.beta.8/app/controllers/concerns/lookbook/targetable_concern.rb:70:in `map'
/usr/local/bundle/gems/lookbook-2.0.0.beta.8/app/controllers/concerns/lookbook/targetable_concern.rb:70:in `set_params'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:201:in `block in halting'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:513:in `each'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:110:in `block in run_callbacks'
/usr/local/bundle/gems/actiontext-6.0.5.1/lib/action_text/rendering.rb:19:in `with_renderer'
/usr/local/bundle/gems/actiontext-6.0.5.1/lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/usr/local/bundle/gems/marginalia-1.11.1/lib/marginalia.rb:109:in `record_query_comment'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/notifications.rb:180:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/notifications.rb:180:in `instrument'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/abstract_controller/base.rb:136:in `process'
/usr/local/bundle/gems/actionview-6.0.5.1/lib/action_view/rendering.rb:39:in `process'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_controller/metal.rb:190:in `dispatch'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_controller/metal.rb:254:in `dispatch'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/journey/router.rb:32:in `each'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/routing/route_set.rb:834:in `call'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/engine.rb:527:in `call'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/railtie.rb:190:in `public_send'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/railtie.rb:190:in `method_missing'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/journey/router.rb:32:in `each'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/routing/route_set.rb:834:in `call'
/usr/local/bundle/gems/omniauth-2.1.0/lib/omniauth/strategy.rb:202:in `call!'
/usr/local/bundle/gems/omniauth-2.1.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/static.rb:126:in `call'
/usr/local/bundle/gems/dragonfly-1.4.0/lib/dragonfly/middleware.rb:14:in `call'
/usr/local/bundle/gems/meta_request-0.7.3/lib/meta_request/middlewares/app_request_handler.rb:15:in `call'
/usr/local/bundle/gems/meta_request-0.7.3/lib/meta_request/middlewares/meta_request_handler.rb:15:in `call'
/usr/local/bundle/gems/bullet-7.0.2/lib/bullet/rack.rb:12:in `call'
/usr/local/bundle/gems/rack-attack-6.6.1/lib/rack/attack.rb:103:in `call'
/usr/local/bundle/gems/rack-attack-6.6.1/lib/rack/attack.rb:103:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/static.rb:161:in `call'
/usr/local/bundle/gems/remotipart-1.4.4/lib/remotipart/middleware.rb:32:in `call'
/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/etag.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/conditional_get.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/cookies.rb:654:in `call'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/migration.rb:567:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/usr/local/bundle/gems/appsignal-3.0.27/lib/appsignal/rack/rails_instrumentation.rb:19:in `call'
/usr/local/bundle/gems/better_errors-2.9.1/lib/better_errors/middleware.rb:87:in `protected_app_call'
/usr/local/bundle/gems/better_errors-2.9.1/lib/better_errors/middleware.rb:82:in `better_errors_call'
/usr/local/bundle/gems/better_errors-2.9.1/lib/better_errors/middleware.rb:60:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/usr/local/bundle/gems/rack-contrib-2.3.0/lib/rack/contrib/response_headers.rb:19:in `call'
/usr/local/bundle/gems/meta_request-0.7.3/lib/meta_request/middlewares/headers.rb:18:in `call'
/usr/local/bundle/gems/web-console-3.7.0/lib/web_console/middleware.rb:135:in `call_app'
/usr/local/bundle/gems/web-console-3.7.0/lib/web_console/middleware.rb:22:in `block in call'
/usr/local/bundle/gems/web-console-3.7.0/lib/web_console/middleware.rb:20:in `catch'
/usr/local/bundle/gems/web-console-3.7.0/lib/web_console/middleware.rb:20:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/rack/logger.rb:37:in `call_app'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/rack/logger.rb:26:in `block in call'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/rack/logger.rb:26:in `call'
/usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/bundle/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/method_override.rb:24:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/runtime.rb:22:in `call'
/usr/local/bundle/gems/activesupport-6.0.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/static.rb:126:in `call'
/usr/local/bundle/gems/dragonfly-1.4.0/lib/dragonfly/cookie_monster.rb:9:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/sendfile.rb:110:in `call'
/usr/local/bundle/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
/usr/local/bundle/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/usr/local/bundle/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiler.rb:237:in `call'
/usr/local/bundle/gems/webpacker-5.4.3/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
/usr/local/bundle/gems/rack-proxy-0.7.2/lib/rack/proxy.rb:67:in `call'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/engine.rb:527:in `call'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/railtie.rb:190:in `public_send'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/railtie.rb:190:in `method_missing'
/usr/local/bundle/gems/puma-5.6.5/lib/puma/configuration.rb:252:in `call'
/usr/local/bundle/gems/puma-5.6.5/lib/puma/request.rb:77:in `block in handle_request'
/usr/local/bundle/gems/puma-5.6.5/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/usr/local/bundle/gems/puma-5.6.5/lib/puma/request.rb:76:in `handle_request'
/usr/local/bundle/gems/puma-5.6.5/lib/puma/server.rb:443:in `process_client'
/usr/local/bundle/gems/puma-5.6.5/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by allmarkedup** [comment] 2023-03-30 20:13
Hey @unikitty37, thanks for the bug report - I've taken a look and I've spotted the problem is so I'll get that fixed up now and it'll go out in the next beta release. 

> I'm not sure if this is Zeitwerk-related; we had to rename some files just to get Rails to start once the lookbook gem was added, even though it started just fine without the gem in place. Does Lookbook make any changes to the autoloader configuration?

The params bug is _not_ a Zeitwerk issue, but I'd be very interested to find out a bit more about the problems you describe above. Lookbook absolutely should not be stopping Rails running so I'm very keen to figure out what is going on here!

Do you think you could give me some examples of what you needed to do to get it working? A one or two examples of file paths with the changes needed in each one would be really helpful. 

Also, if possible, could you paste in the output of the "copy debug data" link in the Lookbook debug menu? With any sensitive info redacted, if needed. It's the little `?` icon in the top right of the header:

<img width="234" alt="CleanShot 2023-03-30 at 21 00 19" src="https://user-images.githubusercontent.com/126726/228951097-94c56a73-bf71-4151-b792-b37697ed0eae.png">

I don't want to take up too much of you time but any more info on this would be much appreciated 🙏

Lookbook _does_ add some additional paths to the autoloader, but it doesn't tinker with any wider Zeitwerk settings outside of autoloading it's own files. However there may still be some conflict somewhere that is causing the issues you ran into.

Thanks for all the detailed info and I'll let you know when a fix is ready to test.

**Comment by allmarkedup** [comment] 2023-03-30 23:28
@unikitty37 I've just released beta.9 that should fix the NameError issue you are seeing. Let me know how you get on when you get a chance to try it.

I'll leave this issue open for now to track the conversation around the Zeitwerk problem but I may split that out into it's own issue once I know a bit more about it.

**Comment by unikitty37** [comment] 2023-03-31 08:08
> Hey @unikitty37, thanks for the bug report - I've taken a look and I've spotted the problem is so I'll get that fixed up now and it'll go out in the next beta release.

Thanks! Beta 9 seems to have fixed it 🎉 
 
> > I'm not sure if this is Zeitwerk-related; we had to rename some files just to get Rails to start once the lookbook gem was added, even though it started just fine without the gem in place. Does Lookbook make any changes to the autoloader configuration?
> 
> The params bug is _not_ a Zeitwerk issue, but I'd be very interested to find out a bit more about the problems you describe above. Lookbook absolutely should not be stopping Rails running so I'm very keen to figure out what is going on here!
> 
> Do you think you could give me some examples of what you needed to do to get it working? A one or two examples of file paths with the changes needed in each one would be really helpful.

Sure; the file that was throwing the error was `lib/redacted_integration/nomination_helpers.rb`, which had to be moved to `lib/redacted_integration/redacted_integration/nomination_helpers.rb`.

```ruby
module RedactedIntegration
  module NominationHelpers
    ...
  end
end
```

(there were three or four others in the same folder that needed to be moved one deeper)

and the file lib/redacted_integration.rb had to have all the `require_relative` paths changed similarly.

> Also, if possible, could you paste in the output of the "copy debug data" link in the Lookbook debug menu? With any sensitive info redacted, if needed. It's the little `?` icon in the top right of the header:
> 
> <img alt="CleanShot 2023-03-30 at 21 00 19" width="234" src="https://user-images.githubusercontent.com/126726/228951097-94c56a73-bf71-4151-b792-b37697ed0eae.png">

```json
{
  "version": "2.0.0.beta.8",
  "env": "development",
  "config": {
    "project_name": "REDACTED",
    "project_logo": null,
    "preview_paths": [
      "test/components/previews",
      "/workdir/spec/components/stories"
    ],
    "preview_display_options": {
    },
    "preview_controller": "ViewComponentsController",
    "preview_template": "lookbook/previews/preview",
    "preview_inspector": {
      "main_panels": [
        "preview",
        "output"
      ],
      "drawer_panels": [
        "source",
        "notes",
        "params",
        "*"
      ]
    },
    "preview_embeds": {
      "enabled": true,
      "policy": "SAMEORIGIN",
      "panels": false,
      "actions": [

      ],
      "scenarios": [

      ],
      "display_option_controls": true
    },
    "preview_layout": "component_preview",
    "preview_disable_action_view_annotations": true,
    "preview_type_default": "view_component",
    "preview_sort_scenarios": false,
    "page_controller": "Lookbook::PageController",
    "page_route": "pages",
    "page_paths": [
      "test/components/docs"
    ],
    "page_extensions": [
      "html.*",
      "md.*"
    ],
    "page_options": {
    },
    "markdown_options": {
      "tables": true,
      "fenced_code_blocks": true,
      "disable_indented_code_blocks": true,
      "strikethrough": true,
      "highlight": true,
      "with_toc_data": true,
      "lax_spacing": true
    },
    "highlighter_options": {
      "theme": "github",
      "dark": false
    },
    "component_paths": [
      "app/views",
      "app/components"
    ],
    "reload_on_change": true,
    "live_updates": true,
    "listen_paths": [

    ],
    "listen_extensions": [
      "rb",
      "html.*"
    ],
    "ui_theme": "indigo",
    "ui_theme_overrides": {
      "accent_50": "#f3fafb",
      "accent_100": "#e8f5f7",
      "accent_200": "#c5e5eb",
      "accent_300": "#a2d5df",
      "accent_400": "#5cb6c7",
      "accent_500": "#1696af",
      "accent_600": "#14879e",
      "accent_700": "#117183",
      "accent_800": "#0d5a69",
      "accent_900": "#0b4a56"
    },
    "ui_favicon": true,
    "log_level": 2,
    "log_use_rails_logger": true,
    "debug_menu": true,
    "experimental_features": false,
    "links": {
      "docs": "https://v2.lookbook.build",
      "demo": "https://v2-demo.lookbook.build",
      "repo": "https://github.com/ViewComponent/lookbook/tree/v2"
    },
    "using_view_component": true,
    "dependencies": {
      "actioncable": true,
      "listen": true,
      "view_component": true
    },
    "panels": {
    },
    "inputs": {
    },
    "tags": {
    }
  }
}
```

**Comment by allmarkedup** [comment] 2023-04-02 07:55
> Thanks! Beta 9 seems to have fixed it 🎉

Excellent! 🙂 

> Sure; the file that was throwing the error was lib/redacted_integration/nomination_helpers.rb, which had to be moved to lib/redacted_integration/redacted_integration/nomination_helpers.rb.

This is very odd - the `lib` directory is definitely not where I would have not expected autoloading issues caused by a Lookbook integration! I'll try and recreate the problem at my end and see if I can get top the bottom of it. Really appreciate you getting back to me with more details about it.

I don't want to take up any more of your time but if you have a chance could you possibly see if you have the same autoloading issue with the previous beta.4 version? There was a small change to autoloading in beta.5 that shouldn't have any impact on the `lib` directory but it would be good to rule it out if possible.

I'm going to close this issue down and open a fresh one to track the autoloading problem - I'll link to this conversation from it and I'll update there once I have figured out what is going on.

**Closed by allmarkedup** 2023-04-02 07:55 UTC
Labels: bug, v2.0-beta
