### ISSUE TITLE
Devise’s authenticate block breaks previews

### ISSUE THREAD

**Issue by nicieja** [ViewComponent/lookbook#445] opened 2023-04-29 09:09 UTC
### Describe the bug

Am I the only one who gets `undefined method 'authenticate!' for nil:NilClass` when I use Devise’s `authenticate` block in routes like this: https://github.com/changepack/changepack/blob/5d27756550051dd6adafe52e8ecc83186bf12ea9/config/routes.rb#L9

### To Reproduce

1. `git clone git@github.com:changepack/changepack.git`
2. Go to http://localhost:3000/lookbook
3. Click on the only available component
4. See below.

![Screenshot 2023-04-29 at 11 07 47](https://user-images.githubusercontent.com/333677/235294711-9355a36d-1300-46fe-b207-e99a47ff3bf8.png)

### Expected behavior

I expect to see the component previewed. When I comment the `authenticate` block out, everything works perfectly.

### Version numbers 

Please complete the following information:

* Lookbook: 2.0.0
* ViewComponent: 3.0.0
* Rails: 7.0.4
* Ruby: 3.2.1

**Comment by guillaumebriday-pa** [comment] 2023-05-01 14:43
I got the exact same issue

**Comment by allmarkedup** [comment] 2023-05-03 14:55
@nicieja thanks for bringing this to my attention - I don't use Devise personally so I haven't run into this before, but I can replicate it with the repo you provided so just looking into it now. Will hopefully have a fix up soon 👍

**Comment by allmarkedup** [comment] 2023-05-03 16:33
Hey @nicieja @guillaumebriday-pa - I believe I have a fix for this now in PR #450.

It works for me in the `changepack/changepack` app now but it would be great to get confirmation if you have a chance to give it a try by bundling Lookbook from the `devise-preview-fix` branch.

It is a bit of a hack to be honest - the issue you are seeing is actually being caused by a workaround for another bug. But if this works for now then I'll ship it for now and hopefully spend a bit of time on unpicking the actual root cause of the problem when I have a little more time.

I'm going to go a little more testing but once I'm happy (and unless I hear back that it is still causing issues for either of you) I'll merge it in and get it out in the next release (which will be v1.0.1).

**Comment by allmarkedup** [comment] 2023-05-03 16:34
(@nicieja as an aside, Changepack looks very interesting! I'm keen to dig in a bit more when I get a chance 😊)

**Comment by guillaumebriday-pa** [comment] 2023-05-03 19:15
The fix actually works for me as well! 

Thank you for your reactivity! 🙏

**Comment by guillaumebriday-pa** [comment] 2023-05-03 19:18
Awesome 🙏 , can you release the 2.0.1?

**Comment by allmarkedup** [comment] 2023-05-03 22:25
@guillaumebriday-pa @nicieja 2.0.1 is now out that includes the fix for this. Thanks for your help!

**Closed by allmarkedup** 2023-05-03 22:25 UTC
Labels: bug, v2.x

**Comment by nicieja** [comment] 2023-05-04 20:32
@allmarkedup Didn’t look at GitHub yesterday but I can confirm that the fix works for me too. Thanks!

> (as an aside, Changepack looks very interesting! I'm keen to dig in a bit more when I get a chance 😊)

🙏 Glad you like it!
