### ISSUE TITLE
Dynamic or permanent view cache invalidation

### ISSUE THREAD

**Issue by tleish** [ViewComponent/lookbook#303] opened 2023-01-26 04:39 UTC
### Is your feature request related to a problem? Please describe

We enable Rails caching in development mode so that we can see if our application is properly invalidating cache.  We also mounted lookbook as part of our main application so other developers could have easy access to the latest styles.  Because of this, when making lookbook entries on dev machines, changes do not show up unless disabling dev caching.  When other devs pull the latest, they do not know there are any updates to the styles.  They would have to reset their cache every time they pull the latest.  This extra step of disabling cache not a normal process.

### Describe the solution you'd like

It would be great if lookbook could be better at invalidating caching when new files are added/updated.  

### Describe alternatives you've considered

Alternatively, add the ability to permanently disable caching (for local dev environments).  I saw a suggestion to use `tmp/cache/lookbook-digest` a as described by @palkan in https://github.com/ViewComponent/lookbook/issues/98

I've searched the documentation. so if there's already a way to do this I could not find it

**Comment by allmarkedup** [comment] 2023-01-31 23:41
Hey @tleish, thanks for this. I can see your issue here and we definitely need to find a fix for this as there is no way to currently disable Lookbook's caching I'm afraid.

I'll see if I can find a nice way to handle the cache invalidation - if not a config option is always possible, but it would be nice to not need one.

I'll let you know as soon as I've got something for you to test out.

**Comment by allmarkedup** [comment] 2023-02-01 01:31
@tleish I've just opened a PR to (hopefully) address this issue - would you mind testing it out to see if it fixes things for you?

**Comment by tleish** [comment] 2023-02-01 18:57
Thanks for the PR.  Initially it did not work for me.  Then stepping through the code I found that `filewatcher#start` is never executed from 

```ruby
  # lookbook/engine.rb

   config.after_initialize do
      if Rails.application.respond_to?(:server)
        Rails.application.server { file_watcher.start if listen? }
      elsif process.supports_listening?
        file_watcher.start if listen?
      end
    end
```

`Rails.application.respond_to?(:server) => true`, but `Rails.application.server` never executes the block `file_watcher.start if listen?`.

When temporarily changing to:

```diff
  # lookbook/engine.rb

config.after_initialize do
-   if Rails.application.respond_to?(:server)
-     Rails.application.server { file_watcher.start if listen? }
-   elsif process.supports_listening?
-     file_watcher.start if listen?
-   end
+  file_watcher.start if listen?
end
```

It seems to work (although I didn't get deep into testing).  Is it related to rails version?

- Rails 6.1.5

**Comment by allmarkedup** [comment] 2023-02-02 13:44
Hey @tleish - okay, something else may be going on here then. Can you check the `config.ru` file in the root directory of your app and see if it has the following line at the end of it?

```rb
Rails.application.load_server
```

This is [included in all new Rails installs](https://github.com/rails/rails/blob/21f8b46485b8afa045b3aa0f219f5b31f0d69cf3/railties/lib/rails/generators/rails/app/templates/config.ru.tt#L6) but doesn't always seem to be added when updating apps from previous versions.

If it isn't in there can you add it and see if you have any more luck?

**Comment by hoangnguyen1010** [comment] 2023-02-14 09:55
I can confirm that this PR works on `rails (7.0.4.2)`

**Comment by allmarkedup** [comment] 2023-02-14 15:42
thanks @hoangnguyen1010 - the PR will be included in the next release 👍

**Comment by allmarkedup** [comment] 2023-02-14 20:05
@tleish I've just released [v1.5.3](https://github.com/ViewComponent/lookbook/releases/tag/v1.5.3) that contains the cache-invalidation PR, so I'm going to go ahead and close this issue now.

If the suggestion above doesn't work for getting the other part of your issue working it's probably best to open another issue directly dealing with that. Let me know how you get on when you have a chance to take a look.

**Closed by allmarkedup** 2023-02-14 20:05 UTC
Labels: feature request

**Comment by justinperkins** [comment] 2023-02-14 23:00
Jumping in here for a +1 on this issue. Lookbook was driving me absolutely crazy last week, anytime I changed _certain_ details of a component preview it seemed like I had to stop/start my docker container I'm running my app in. My coworker kept telling me something was wrong with my setup because they've never experienced any issues. Then I finally realized the difference: I run with caching turned on in dev, they do not.

Just for my own curiosity, is there a PR discussion somewhere that explains _why_ caching is part of lookbook in the first place? My understanding is it only runs in development, where caching generally gets in the way more than it helps. Lookbook seems quite peppy when caching is disabled.

**Comment by tleish** [comment] 2023-02-14 23:51
@allmarkedup - sorry for the late feedback.  I tried the branch (not not the release, which I assume has the same changes). Using the updated branch and also updating my `config.ru`, I've only tested it a short time but it appears to be much easier to work on lookbook previews and to see others changes when running rails in cache mode.  I'll update if I discover otherwise.

Thanks for the fix.

**Comment by allmarkedup** [comment] 2023-02-15 00:06
@tleish no worries, glad it seems to have fixed it for you :-)

@justinperkins sorry it's been causing you headaches! Hopefully the latest release should fix the issue, if not feel free to open another or reopen this one and I'll try to help.

The sidebar is cached because quite a few apps do actually run Lookbook in production and for large projects with a lot of components the sidebar rendering was actually pretty slow. Hopefully with this fix now we should get the best of both worlds.

**Comment by hoangnguyen1010** [comment] 2023-02-15 10:00
Thanks @allmarkedup , the release is perfect, works like a charm now.

**Comment by allmarkedup** [comment] 2023-02-15 10:18
@hoangnguyen1010 fantastic, thanks for letting me know! :-)
